package dao;
// Generated 15-May-2024 00:36:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name="books"
    ,catalog="db_book"
)
public class Books  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String author;
     private String description;
     private BigDecimal price;
     private Date publishedDate;

    public Books() {
    }

	
    public Books(String title, String author, BigDecimal price) {
        this.title = title;
        this.author = author;
        this.price = price;
    }
    public Books(String title, String author, String description, BigDecimal price, Date publishedDate) {
       this.title = title;
       this.author = author;
       this.description = description;
       this.price = price;
       this.publishedDate = publishedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="author", nullable=false)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false, precision=10)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="published_date", length=10)
    public Date getPublishedDate() {
        return this.publishedDate;
    }
    
    public void setPublishedDate(Date publishedDate) {
        this.publishedDate = publishedDate;
    }




}


